### ISSUE TITLE
No autocompletion for static global resources

### ISSUE THREAD

**Issue by sebbert** [fusetools/Fuse.SublimePlugin#19]
For instance [TransformOrigins.TopLeft](https://github.com/fusetools/fuselibs/blob/f2fc2e51f315ff12520a977939ec543fdf2d9d26/Source/Fuse.Elements/Element.Transform.uno#L42)

**Comment by Tapped** [comment]
We have an internal ticket for this, this is not specific for the Sublime Plugin. 
https://github.com/fusetools/Fuse/issues/87
