### ISSUE TITLE
Normalize preview commands across editors

### ISSUE THREAD

**Issue by sebbert** [fusetools/Fuse.SublimePlugin#21]
For instance, the command for android preview in Sublime is called `Fuse: Local Preview`, while in Atom it is `Fuse: Preview Local`.

This can get annoying in cases where you use abbreviations to run a command. In sublime I have to type `flp`, while in atom it's `fpl`.

I suggest the naming scheme used currently in Atom, since it follows the level of scope (`Fuse` > `Preview` > `Local`)

**Comment by Tapped** [comment]
I agree, I'll merge it tomorrow.
