### ISSUE TITLE
[BUG] Fuse could not be found

### ISSUE THREAD

**Issue by dn5** [fusetools/Fuse.SublimePlugin#28]
Some of you have seen my tweet right here @ [dn5__](https://twitter.com/dn5__/status/758365996658950144).
This happened after installation of Windows 7 Ultimate x64, and Fusetools including latest build of Sublime Text available to me. Running the Sublime Text **Preview** from Fuse plugin, occurs with following message:

![1](https://pbs.twimg.com/media/CoZBsZHWcAAO72M.jpg:large)

Initial method call is in [fuse.py](https://github.com/fusetools/Fuse.SublimePlugin/blob/1c12464a59ee6e0473c4f37f28b5e446e6a5fa90/fuse.py#L221).  

_Logged info:_
2016-07-27 20:10:40,747 [4320] INFO Calling subprocess '['fuse', 'daemon', '-b']'  

I saw the line `start_daemon = [path, "daemon", "-b"]` and investigated : 

`fuse.py:212:subprocess.check_output(start_daemon, creationflags=CREATE_NO_WINDOW, stderr=subprocess.STDOUT)`.

**Comment by dn5** [comment]
Oh, a hotfix:  
Launch from command prompt: **fuse daemon -d**. Logged details are correct and sublime text can preview it. Seems like removing the background parameter solves the problem. Can you check this out? Thank you.

**Comment by dn5** [comment]
Any update on this?

**Comment by knatten** [comment]
Hi, is this still an issue? You link to https://camo.githubusercontent.com/7b018aea3cde8213b603df4f559fa625b968c695/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f436f5a42735a48576341414f37324d2e6a70673a6c61726765 is not working.

**Comment by dn5** [comment]
Not on my side after clean reinstallation of operating system. I'd close this.
